externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort

defaultInitContainers:
  autoDiscovery:
    enabled: true

serviceAccount: 
  create: true

rbac:
  create: true

controller:
  replicaCount: 3
  automountServiceAccountToken: true

broker:
  automountServiceAccountToken: true

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT