
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  vertices:
    - name: in
      volumes:
        - name: kafka-config-volume
          configMap:
            name: raw-consumer-config
            items:
              - key: user.configuration
                path: user.configuration.yaml
              - key: consumer.properties
                path: consumer.properties
      scale:
        min: 1
        max: 1
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-java/kafka-java:v0.4.0
            args: [ "--spring.config.location=file:/conf/user.configuration.yaml", "--consumer.properties.path=/conf/consumer.properties" ]
            imagePullPolicy: Always
            volumeMounts:
              - name: kafka-config-volume
                mountPath: /conf

    - name: udf
      scale:
        min: 1
      udf:
        container:
          image: docker.io/keeyiahn/udf:latest
          imagePullPolicy: Always

    - name: error-out
      scale:
        min: 1
      sink:
        log: {}

    - name: kafka-out
      volumes:
        - name: kafka-config-volume
          configMap:
            name: raw-producer-config
            items:
              - key: user.configuration
                path: user.configuration.yaml
              - key: producer.properties
                path: producer.properties
      scale:
        min: 1
        max: 1
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-java/kafka-java:v0.4.0
            args: [ "--spring.config.location=file:/conf/user.configuration.yaml", "--producer.properties.path=/conf/producer.properties" ]
            imagePullPolicy: Always
            volumeMounts:
              - name: kafka-config-volume
                mountPath: /conf
  edges:
    - from: in
      to: udf

    - from: udf
      to: error-out
      conditions:
        tags:
          values:
            - error-tag

    - from: udf
      to: kafka-out
      conditions:
        tags: 
          operator:
          values:
            - users-tag
